specVersion: 1.0.0
name: moonbeam-explorer
version: 1.0.0
runner:
  node:
    name: "@subql/node"
    version: ">=0.35.0"
  query:
    name: "@subql/query"
    version: ">=0.16.0"

description: Subquery for moonbeam blockchain explorer
repository: https://github.com/AlphabitTeam/moonbeam-subquery

schema:
  file: ./schema.graphql

network:
  endpoint: wss://moonbeam.api.onfinality.io/public-ws
  genesisHash: "0xfe58ea77779b7abda7da4ec526d14db9b1e9cd40a217c34892af80a9b332b76d"
  dictionary: "https://api.subquery.network/sq/subquery/moonbeam-dictionary"
  chaintypes:
    file: "./dist/chaintypes.js"

dataSources:
  - kind: substrate/Runtime
    startBlock: 4887
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
        - handler: handleCall
          kind: substrate/CallHandler
  - kind: substrate/Moonbeam
    startBlock: 4887
    processor:
      file: "./node_modules/@subql/contract-processors/dist/moonbeam.js"
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleMoonbeamEvent
          kind: substrate/MoonbeamEvent
        - handler: handleMoonbeamCall
          kind: substrate/MoonbeamCall