specVersion: 0.2.0
name: moonbeam-subquery
version: 1.0.0
description: Subquery for moonbeam blockchain explorer
repository: https://github.com/parascan-xyz/moonbeam-subquery

schema:
  file: ./schema.graphql

network:
  endpoint: wss://moonbeam.api.onfinality.io/public-ws
  genesisHash: '0xfe58ea77779b7abda7da4ec526d14db9b1e9cd40a217c34892af80a9b332b76d'
  dictionary: 'https://api.subquery.network/sq/subquery/moonbeam-dictionary'
  #chaintypes:
  #  file: "./types.yaml"

dataSources:
  - kind: substrate/Runtime
    startBlock: 200_000
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
        - handler: handleCall
          kind: substrate/CallHandler
